// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLcaiZeNz0pkg4SzhRZpe1w0Wk7IjStJI',
    appId: '1:415399221456:android:d64b802bbd40925798a6d5',
    messagingSenderId: '415399221456',
    projectId: 'game-app-bdcf1',
    storageBucket: 'game-app-bdcf1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZbQpUaC8Z5Yi4lhXqbLKbIMnLg_hOkFg',
    appId: '1:415399221456:ios:35f9fad431bbed7798a6d5',
    messagingSenderId: '415399221456',
    projectId: 'game-app-bdcf1',
    storageBucket: 'game-app-bdcf1.firebasestorage.app',
    iosBundleId: 'com.indnkt78.mainSony',
  );
}
